### PR TITLE
EventFactory: add rules for the 2022 steward elections

### PR DESCRIPTION
**Pull request by MarcoAurelioWM**
Fixes https://github.com/Pathoschild/Wikimedia-contrib/issues/157

### CODE REVIEW

**Comment by MarcoAurelioWM** [comment]
Adding @urbanecm and @tks4fish for review.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Thanks! This looks fine to me; I'll merge and deploy it when you unmark it as draft.

**Comment by MarcoAurelioWM** [comment]
> Thanks! This looks fine to me; I'll merge and deploy it when you unmark it as draft.

Thanks for the review. Once we decide the very exact dates and hours I'll make the necessary amendments and let you know.

Happy new year 2022, best wishes.

**Comment by urbanecm** [comment]
Code LGTM. AFAIK, exact eligibility rules (dates and numbers) need to be decided/confirmed by the ElectCom (which will be announced on-wiki within few days).

**Comment by urbanecm** [comment]
LGTM.

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged and deployed. Thanks for the PR!

**Pull request merged**
