### PR TITLE
Add POTY 2022

### PR DESCRIPTION
**Pull request by legoktm**
Thanks!

### CODE REVIEW

**Comment by Pathoschild** [comment]
The event page doesn't seem to exist yet. Should we wait until it's created, so the tool doesn't have a broken link (and I can double-check the rules)?

**Comment by legoktm** [comment]
Oops yeah, I'll create that tomorrow. The rules are going to be the same as last year (https://commons.wikimedia.org/wiki/Commons:Picture_of_the_Year/2021/Rules) - I'm going to move them to a non-year subpage so we don't have to keep copy and pasting them every year.

**Comment by legoktm** [comment]
@Pathoschild the event page and rules now exist :-)

**Review by Pathoschild — APPROVED** [review]

**Comment by Pathoschild** [comment]
Merged and deployed. Thanks for the pull request!

**Pull request merged**
